### ISSUE TITLE
Recomendation

### ISSUE THREAD

**Issue by amunhoz** [LuKks/like-mysql#1]
My proposal  to improve it:

`let orders = await connMM.select("main_orders", "*", 'createdAt >= ' + moment().add(-6,"day").unix())    `

```
function select (table, cols, find, ...values) {
  if (Array.isArray(cols)) cols = cols.map(c => '`' + c + '`').join(', ');
  find = parseFind(find);
  return execute.call(this, `SELECT ${cols} FROM ${table}${find}`, values);
}
```

**Comment by LuKks** [comment]
I like it. Would you like to make a pull request?

**Comment by LuKks** [comment]
I'll close the issue due inactivity. Also, now I prefer to keep a single datatype for the parameter.
